language: python

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install --upgrade -e.[test]

before_script:
  - mkdir ~/.fonts
  - cp ./test/resources/*.*tf ~/.fonts
  - fc-cache -f -v

script:
  - python setup.py test

sudo: false
